language: java
sudo: disabled
install: false

jdk:
- oraclejdk8

jobs:
    include:
      - stage: "Tests"
        name: "Checkstyle"
        script: gradle checkstyleMain
      - stage: "Tests"
        name: "Unit tests"
        script: gradle test
        
cache:
  directories:
- '$HOME/.m2/repository'
