language: java
install: false

jdk:
    - oraclejdk8

jobs:
    include:
      - stage: "Tests"
        name: "Checkstyle"
        script: gradle checkstyleMain
      - stage: "Tests"
        name: "Unit tests"
        script: gradle test
      - stage: "Success"
        name: "Codecov upload"
        script: bash <(curl -s https://codecov.io/bash)
        
cache:
  directories:
    - '$HOME/.m2/repository'
