CREATE TABLE IF NOT EXISTS "RECOMMENDATION"(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR VARCHAR(255),
    NAME  VARCHAR(255),
    ISBN VARCHAR(255),
    TYPE VARCHAR(255),
    URL VARCHAR(255),
    DESCRIPTION VARCHAR(10000)
);
